### ISSUE TITLE
[Feature] Flag named volume subpaths being mapped directly

### ISSUE THREAD

**Issue by barcar** [zavoloklom/docker-compose-linter#116]
## Feature Description

Flag a warning for compose files where a named volume subpath is directly mounted.

## Problem this Feature Will Solve

Until recently, Docker and Docker Compose did not support mounting subpaths (or files) from named volumes. This resulted in an ugly workaround which combined volume and bind mounts like this:
```
    volumes:
      - samba:/mnt/samba
      - /var/lib/docker/volumes/samba/_data/smb.conf:/etc/samba/smb.conf
```
whereas now you can do this more elegantly using the subpath option for a named volume:
```
    volumes:
      - type: volume
        source: samba
        target: /etc/samba/smb.conf
        volume:
          nocopy: true
          subpath: smb.conf
```
## Proposed Solution

My proposal is to add a rule to detect this old workaround and flag that the new subpath option should be used. The rule could be something like:

- Is there a bind mount which refers to the path of a named volume (e.g. /docker/volumes/samba)
- AND, is there a named volume mount to that same named volume (e.g. samba)

Ideally this could be extended to directly fix the ugly volume by re-parsing it to use the new subpath format.

## Alternatives Considered

I could run find and sed over my compose files.

## Additional Context

None
