### ISSUE TITLE
linter config scheme only allows 2 Properties

### ISSUE THREAD

**Issue by janitor-of-code** [zavoloklom/docker-compose-linter#122]
Great tool you got there, it really has been missing in our 'infrastructure as code' workflow so thank you!  

I've stumbled upon a slight issue:  
The scheme for `.dclintrc` appears to allow only 2 Items while also demanding the level number which leaves only 1 option.  

I was trying to set the following up:
```yaml
service-keys-order:
  - 1
  - groupOrder:
      - Core Definitions
      - Service Dependencies
      - Runtime Behavior
      - Security and Execution Context
      - Environment Configuration
      - Data Management and Configuration
      - Networking
      - Operational Metadata
   - groups: 
      Security and Execution Context:
        - user
        - location
        - security_opt  # adding this
```

and it seems I have to choose between `groupOrder` and `groups`

I presume line 40: `"maxItems": 2` from docker-compose-linter/schemas/linter-config.schema.json is what's causing that

Thanks in advance.

**Comment by zavoloklom** [comment]
@janitor-of-code Hi!

Apologies for the delayed response.

It's actually not an issue — you just need to do it like this:

```
service-keys-order:
  - 1
  - groupOrder:
    - Core Definitions
    - Service Dependencies
    - Runtime Behavior
    - Security and Execution Context
    - Environment Configuration
    - Data Management and Configuration
    - Networking
    - Operational Metadata
    groups:
      Security and Execution Context:
      - user
      - location
      - security_opt
```

Let me know if that helps or if you need further assistance.
