### ISSUE TITLE
Running dclint breaks long lines without any sense and making them unusable

### ISSUE THREAD

**Issue by dtap001** [zavoloklom/docker-compose-linter#136]
## Version
2.2.2

This is the original yaml part before linting:
```
   logging:
      options:
        labels: "job=docker,container_name={{.Name}},server_serial=${SERVER_EXTENDED_SERIAL}"
```

## Command used to run

 npx dclint  --fix --debug docker-compose.yaml            

.dclintrc file content:   

```
{
  "$schema": "https://raw.githubusercontent.com/zavoloklom/docker-compose-linter/refs/heads/main/schemas/linter-config.schema.json",
  "rules": {
    "no-version-field": 2,
    "require-quotes-in-ports": 2,
    "no-unbound-port-interfaces": 0,
    "require-project-name-field": 0,
    "service-ports-alphabetical-order": 1,
    "service-dependencies-alphabetical-order": 1,
    "service-image-require-explicit-tag": 2,
    "no-duplicate-exported-ports": 2,
    "service-keys-order": [
      1,
      {
        "groupOrder": [
          "Core Definitions",
          "Service Dependencies",
          "Networking",
          "Data Management and Configuration",
          "Environment Configuration",
          "Runtime Behavior",
          "Operational Metadata",
          "Security and Execution Context"
        ]
      }
    ]
  },
  "quiet": false,
  "debug": true,
  "exclude": [
    "tests"
  ]
}
```

Instead of keeping it the same the linter breaks them into multiple line:

```
  logging:
    options:
      labels: "job=docker,container_name={{.Name}},learningspace_serial=${SERVER_EXTE\
        NDED_SERIAL}"
```

Same issue happens here:
Original service:
```
  frontend:
    image:myimage:mytag
    networks:
      - core
    environment:
      TZ: ${TIMEZONE}
    healthcheck:
      test: curl --fail --silent http://127.0.0.1:8080/health | grep -q '{"status":"UP"}' || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
```

After the lint run:
```
  frontend:
    image:myimage:mytag
    networks:
      - core
    environment:
      TZ: ${TIMEZONE}
    healthcheck:
      test: curl --fail --silent http://127.0.0.1:8080/health | grep -q
        '{"status":"UP"}' || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
```

Please help me. I cannot find any configuration regarding this issue.
