### ISSUE TITLE
Error when using in github as action

### ISSUE THREAD

**Issue by natcoso9955** [zavoloklom/docker-compose-linter#158]
## Version
docker.io/zavoloklom/dclint:alpine

Please specify the version of the project where the issue occurred (e.g., `v1.2.3`, `main`, `commit hash`).

## YAML file where the error occurs
N/A

## Command used to run
See below

## Optional configuration (if different from the default)
N/A

## Additional context
Running latest self-hosted github runner
Add any other context about the problem here (Node.js/Docker version, etc.).

## Current behavior (console output)
```bash
Post job cleanup.
/usr/bin/docker exec  5050bd5df74999334[2](https://REDACTED/actions/runs/122690/job/864705?pr=50#step:11:2)02976c85872702ff0896bc0f77f0d964b30649f64ee13f sh -c "cat /etc/*release | grep ^ID"
OCI runtime exec failed: exec failed: unable to start container process: exec: "/__e/node20_alpine/bin/node": stat /__e/node20_alpine/bin/node: no such file or directory: unknown
```

## Expected behavior
Github action should complete and fail if linting doesnt pass, and succeed if it does.

## Action Yaml
```yml
name: Lint Docker Compose

on:
  pull_request:
    paths:
      - '**/docker-compose.yml'
      - '**/docker-compose*.yaml'
      - '**/*.yml'
      - '**/*.yaml'
    branches:
      - Master
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: self-hosted

    container:
      image: zavoloklom/dclint:alpine
      options: --entrypoint=""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Docker container
        run: |
          docker info
          docker run --rm zavoloklom/dclint:alpine /bin/sh -c "which node; cat /etc/*release"

      - name: Run linter
        run: |
          /bin/dclint . -r -f codeclimate -o gl-codequality.json

      - name: Upload code quality artifact
        uses: actions/upload-artifact@v3
        with:
          name: gl-codequality-report
          path: gl-codequality.json
          token: ${{ secrets.GITHUB_TOKEN }}
```
****
