### ISSUE TITLE
invalid-schema error when specifying gw_priority on a network interface.

### ISSUE THREAD

**Issue by CC-Damo** [zavoloklom/docker-compose-linter#185]
## Version

`Release 2.2.2`

## YAML file where the error occurs

```
name: traefik
services:
  traefik:
    image: traefik:3.3.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /letsencrypt:/letsencrypt
      - /config:/etc/traefik/
    env_file:
      - .env
    ports:
      - '0.0.0.0:80:80'
    networks:
      default:
        ipv4_address: 172.16.0.2
        gw_priority: 1
      socket-proxy:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    restart: unless-stopped

networks:
  default:
    name: traefik_default
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
          ip_range: 172.16.1.0/24

  socket-proxy:
    name: socket-proxy
    external: true

```

## Command used to run

`dclint .`

## Optional configuration (if different from the default)

Nothing custom provided. Standard release.

## Additional context

When attempting to run dclint against a compose file which specifies the `gw_priority: 1` property on the network causes the below error:

gw_priority is a valid as per the docker compose documentation https://docs.docker.com/reference/compose-file/services/#gw_priority

## Current behavior (console output)

```
<path redacted>\docker-compose.yml
   1:1     error  ComposeValidationError: instancePath="/services/traefik/networks", schemaPath="#/definitions/list_of_strings/type", message="Validation error: must be array".  invalid-schema

1 problems (1 errors, 0 warnings)
```

## Expected behavior

DCLint should pass with no errors as it does when `gw_priority: 1` is removed.
