### ISSUE TITLE
Ports with different protocols are marked as duplicate by `no-duplicate-exported-ports`

### ISSUE THREAD

**Issue by depado** [zavoloklom/docker-compose-linter#91]
First of all, thanks for the great tool, it works amazing!

## Version

`2.2.1`

## YAML file where the error occurs

```yml
services:
  myservice:
    # ...
    ports:
      - '127.0.0.1:8388:8388/tcp'
      - '127.0.0.1:8388:8388/udp'
      - '127.0.0.1:8888:8888/tcp'
```

## Command used to run

```sh
$ npx dclint compose.yml
```

## Current behavior (console output)

```
/path/to/compose.yml
  54:1     error  Service "myservice" is exporting port "8388" which is already used by service "myservice".  no-duplicate-exported-ports

✖ 1 problems (1 errors, 0 warnings)
```

## Expected behavior

As those ports don't use the same protocol, they shouldn't be marked as duplicated (as far as I understand). Avoiding the issue is very easy by just disabling this rule for this `ports` key, but it's still counter-intuitive I'd say?
